"""
fcrag/reason/agents/retriever_agent.py -- FCRAG 2.0 Retriever Agent
====================================================================
Executes hybrid retrieval for each sub-query generated by the
Decomposer, deduplicates results, and assembles a tri-modal context
package (specs + operational + simu5g).
"""

from __future__ import annotations

import sys
import time
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(ROOT))

from fcrag.reason.state import FCRAGState


# Default collections to search
DEFAULT_COLLECTIONS = ["3gpp_specs", "simu5g_narratives", "alarm_history"]


def retrieve_context(state: FCRAGState) -> dict[str, Any]:
    """
    LangGraph node: Execute hybrid retrieval for each sub-query.

    Reads:  state["sub_queries"], state["fault_type"]
    Writes: retrieved_contexts, latency_breakdown
    """
    t_start = time.perf_counter()

    sub_queries = state.get("sub_queries", [])
    errors = list(state.get("errors", []))

    if not sub_queries:
        errors.append("RetrieverAgent: No sub-queries to retrieve")
        return {
            "retrieved_contexts": [],
            "errors": errors,
        }

    # Late import to avoid circular deps and allow mocking in tests
    from fcrag.retrieve.retriever import HybridRetriever

    try:
        retriever = HybridRetriever()
    except Exception as exc:
        errors.append(f"RetrieverAgent: Failed to init HybridRetriever: {exc}")
        return {
            "retrieved_contexts": [],
            "errors": errors,
        }

    # Retrieve for each sub-query, accumulate unique chunks
    seen_keys: set[str] = set()
    all_contexts: list[dict] = []

    for query in sub_queries:
        try:
            chunks = retriever.retrieve(
                query=query,
                collections=DEFAULT_COLLECTIONS,
                top_k=5,
                use_reranker=True,
            )
            for chunk in chunks:
                key = chunk.dedup_key
                if key not in seen_keys:
                    seen_keys.add(key)
                    all_contexts.append(chunk.to_dict())
        except Exception as exc:
            errors.append(f"RetrieverAgent: Query failed '{query[:50]}...': {exc}")

    t_elapsed = (time.perf_counter() - t_start) * 1000
    latency = dict(state.get("latency_breakdown", {}))
    latency["retrieve_ms"] = t_elapsed

    print(
        f"[RetrieverAgent] {len(sub_queries)} queries -> "
        f"{len(all_contexts)} unique chunks | {t_elapsed:.0f}ms"
    )

    return {
        "retrieved_contexts": all_contexts,
        "latency_breakdown": latency,
        "errors": errors,
    }
